# Generated by Django 5.1 on 2024-12-06 05:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Notes', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='notes',
            name='designation',
            field=models.CharField(default='student', max_length=40),
        ),
        migrations.AddField(
            model_name='notes',
            name='semester',
            field=models.CharField(default='unknown', max_length=50),
        ),
        migrations.AlterField(
            model_name='notes',
            name='description',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='notes',
            name='uploadingdate',
            field=models.DateField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='signup',
            name='contact',
            field=models.CharField(max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='signup',
            name='designation',
            field=models.CharField(default='student', max_length=10),
        ),
    ]
